### ISSUE TITLE
Problem with ReadOnly attribute

### ISSUE THREAD

**Issue by x893** [OnionIoT/source#19]
Hi,
some host/.... packages and feed/packages set ReadOnly (-w) attribute.
Some inside tar fie and some in bootstrap. So pathes can't appyed.
For example:
tools/automake
feeds/packages/libs/db47

I add to include\host-build.mk

ifneq ($(strip $(HOST_UNPACK)),)
  define Host/Prepare/Default
    $(HOST_UNPACK)
    [ ! -d ./src/ ] || $(CP) ./src/* $(HOST_BUILD_DIR)
    @chmod +w -R $(HOST_BUILD_DIR)**
    $(Host/Patch)
  endef
endif

I add to include\package-defaults.mk

ifneq ($(strip $(PKG_UNPACK)),)
  define Build/Prepare/Default
    $(PKG_UNPACK)
    [ ! -d ./src/ ] || $(CP) ./src/. $(PKG_BUILD_DIR)
    @chmod +w -R $(PKG_BUILD_DIR)
    $(Build/Patch)
  endef
endif

Also automake set a-w attribute in bootstrap so i change
tools\automake\Makefile

define Host/Configure
	[ ! -f $(HOST_BUILD_DIR)/bootstrap ] || sed -i 's/chmod a-w/chmod a+w/g' $(HOST_BUILD_DIR)/bootstrap
	(cd $(HOST_BUILD_DIR); $(AM_TOOL_PATHS) STAGING_DIR="" ./bootstrap)
	$(call Host/Configure/Default)
endef

Thanks for OnionIoT
Happy NY

**Comment by greenbreakfast** [comment]
Can you describe what issues are caused by the read only attribute? Ie what you're intending to fix?

**Comment by x893** [comment]
Yes, resolved.
Change bootstrap scripts to remove RO attribute.
See first post.

**Comment by greenbreakfast** [comment]
Hi, this is still very unclear. Is this still an issue or has it been resolved?

If it's still an issue, please give us some information to work with:

* Description of your environment (Linux, Docker image, etc)
* Description of the issue and context
* Expected Behavior
* Observed Behavior
* Steps to reproduce the issue
* What's been attempted to resolve the issue
* What can we do to help?
